version: "3"
services:
  wordpress:
    image: wordpress:latest
    container_name: "prj_wordpress"
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: "db:3306"
    env_file: .env
    volumes:
        - ./wp-content:/var/www/html/wp-content
  db:
    image: mariadb:latest
    container_name: "prj_wordpress_db"
    env_file: .env

  phpmyadmin:
    container_name: "prj_phpmyadmin"
    image: phpmyadmin/phpmyadmin:latest
    ports:
        - 8081:80
    environment:
    - MEMORY_LIMIT=920M
    - UPLOAD_LIMIT=920M
    depends_on:
      - db

volumes:
  db-data:
